### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by v0l** [v0l/snort#2]
Here are a list of bugs and features (& feature improvements) which need to be implemented (in no order):

## New Features
- [ ] DM's
- [x] Delete notes
- [ ] Mentions (Write mentions, with auto-complete)
- [x] Relay list management (Separate page from tab on profile)
- [x] NIP-05 Validation
- [x] Global tab (Currently exists but only for logged out users)
- [ ] Show newest notes (Don't auto load new notes onto the page, hide them behind button)
- [ ] Profile: 
  - [ ] Reaction Tab
  - [x] Followers Tab
  - [x] Follows Tab
- [ ] Notifications (Partially implemented, need service-worker)
- [ ] Link previews (OpenGraph)
- [ ] NIP-05 Shop (Allow creation of NIP-05 links directly from profile page (free/paid services to be connected))
- [ ] User settings:
  - [ ] Allow users to selectively disable reactions [Bandwidth] 
  - [ ] Allow users to selectively disable automatically loading media [Bandwidth/Privacy]
- [ ] Relay load balancing (Epic)
  - [ ] Load balance subscriptions by "splitting" filters where `ids` or `authors` are specified
- [ ] Hash tags:
  - [x] Highlight hashtags
  - [ ] Make hashtags searchable
- [ ] Markdown parsing:
  - [ ] Heading / text formatting / code blocks

## Feature Improvements
- [x] Thread improvements:
  - [x] Group replies into tree structure
  - [x] Visually show thread trees
- [ ] New user UX:
  - [ ] Export keys and explain key security
- [x] Reactions:
  - [x] Show already reacted notes with red icon
- [ ] Timeline improvements:
  - [ ] Show reactions in timeline views
  - [ ] Parse mentioned `pub_key` metadata from timeline (Currently showing names if already cached)
- [ ] Notes:
  - [x] Show time as `HH:mm` when > 60 mins ago
  - [x] Show time as `YYYY-MM-dd HH:mm` when > 24hrs ago
  - [ ] Show tooltip on hover for absolute time
- [ ] LN invoices:
  - [x] Show invoices as expired
  - [ ] Show description and destination (Use Amboss or another source to show alias)
  - [ ] Show QR code first instead of directly opening invoice on desktop
- [ ] Cache:
  - [ ] Use IndexedDB for profile cache so that its searchable (currently only caching in `localStorage`)

## Bugs
- [x] Profile editing still has some cache bugs which make the UX bad
- [x] Clicking mentions redirects twice (once to the mention then once to the note that the mention is on [stopPropagation]) 
- [x] Error checking on parsing LN invoices, sometimes it breaks the page
- [x] Replies have duplicate `p` tags
- [ ] Cleanup `xx-related` recursive subs (stop re-requesting everything when parent changes)

**Comment by verbiricha** [comment]
Created a bunch of issues with what's missing, closing this giga issue.
